services:
  emqx:
    image: emqx/emqx:${EMQX_TAG:-latest}
    container_name: ${EMQX_CONTAINER_NAME:-broker}
    hostname: ${EMQX_HOSTNAME:-broker}
    ports:
      - "${EMQX_MQTT_PORT:-1883}:1883"
      - "${EMQX_WS_PORT:-8083}:8083"
      - "${EMQX_DASHBOARD_PORT:-18083}:18083"
    restart: unless-stopped
    environment:
      EMQX_ALLOW_ANONYMOUS: ${EMQX_ALLOW_ANONYMOUS:-true}
      EMQX_AUTH__USERNAME__PASSWORD__admin: "public"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-etc:/opt/emqx/etc # /home/autem-linux/Documents/emqx-etc:/opt/emqx/etc 
    networks:
      - portainer-network

  mongodb:
    image: mongo:${MONGO_TAG:-latest}
    container_name: ${MONGO_CONTAINER_NAME:-mongodb}
    hostname: ${MONGO_HOSTNAME:-mongodb}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root}
    volumes:
      - mongodb-data:/data/db
    networks:
      - portainer-network

  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_TAG:-latest}
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME:-mongo-express}
    hostname: ${MONGO_EXPRESS_HOSTNAME:-mongo-express}
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOSTNAME:-mongodb}
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - portainer-network

  ignition:
    image: inductiveautomation/ignition:${IGNITION_TAG:-latest}
    container_name: ${IGNITION_CONTAINER_NAME:-ignition-gateway}
    hostname: ${IGNITION_HOSTNAME:-ignition-gateway}
    ports:
      - "${IGNITION_PORT:-8088}:8088"
      - "9043:8043"
      - "62541:62541" #OPCUA
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Europe/Zurich}
      ACCEPT_IGNITION_EULA: ${ACCEPT_IGNITION_EULA:-Y}
      GATEWAY_ADMIN_USERNAME: ${GATEWAY_ADMIN_USERNAME:-admin}
      GATEWAY_ADMIN_PASSWORD: ${GATEWAY_ADMIN_PASSWORD:-password}
      IGNITION_EDITION: ${IGNITION_EDITION:-standard}
      IGNITION_LICENSE_KEY: ${IGNITION_LICENSE_KEY:-}
      GATEWAY_MODULES_ENABLED: ${GATEWAY_MODULES_ENABLED:-opc-ua,perspective,web-developer}
    volumes:
      - ignition-gateway-data:/var/lib/ignition
      - ignition-usr-data:/usr/local/bin/ignition
      - /home/autem-linux/Documents/MongoDB Connector-module.modl:/usr/local/bin/ignition/user-lib/modules/MongoDB Connector-module.modl

    networks:
      - portainer-network
      
volumes:
  emqx-data: {} 
  emqx-log: {}
  emqx-etc: {}
  mongodb-data: {}
  ignition-gateway-data: {}
  ignition-usr-data: {}
  

networks:
  portainer-network:
    external: true